kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.run]
args = ["streamlit", "run", "scripts/src/app.py", "--server.port", "8080", "--server.headless", "true", "--server.address", "0.0.0.0", "--server.enableCORS", "false", "--server.enableXsrfProtection", "false"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/_stcore/health"
